---
title: "TitratorAnalysis"
author: "Shelly Trigg"
date: "12/18/2018"
output: rmarkdown::github_document
---


```{r, echo = FALSE}
library(ggplot2)

setwd("~/Documents/GitHub/P_generosa/Water_Chemistry/analysis/titrator/")

cumu.data <- read.csv("~/Documents/GitHub/P_generosa/Water_Chemistry/data/Titrator/Cumu_TA_Output.csv")
cumu.data$Date <- as.POSIXct(substr(cumu.data$Sample.ID,0,8), format = "%Y%m%d")

fall.data <- cumu.data[which(cumu.data$Date > as.POSIXct("2018-11-06", format = "%Y-%m-%d" )),]
fall.data$treatment <- "treatment"
for(i in 1:length(fall.data$treatment)){
  if(grepl("CRM",fall.data$sample.name[i])){
    fall.data$treatment[i] <- "STD"
  }
  if(grepl("JUNK", fall.data$sample.name[i], ignore.case = TRUE)){
    fall.data$treatment[i] <- "JUNK"
  }
  if(grepl("^3|^4|^6", fall.data$sample.name[i])){
    fall.data$treatment[i] <- "ambient"
  }
  if(grepl("^1|^2", fall.data$sample.name[i])){
    fall.data$treatment[i] <- "low"
  }
  if(grepl("^5", fall.data$sample.name[i])){
    fall.data$treatment[i] <- "varlow"
  }

}                              

#add column for tank
fall.data$tank <- substr(fall.data$sample.name,0,1)
```

CRM percent error
```{r, echo = FALSE}
#read in CRM batch info
CRMs <- read.csv("../../data/Titrator/CRM_Batch_Info.csv", stringsAsFactors = FALSE)
CRMs$Date <- as.POSIXct(strptime(CRMs$Date, format = "%Y%m%d"))

#combine known TAs with measured TAs
CRMpererr <- merge(fall.data[which(substr(fall.data$sample.name,0,3)=="CRM"),c("Date","Sample.ID","TA")], CRMs, by = "Date")
#calculate percent error
CRMpererr$percerr <- abs(CRMpererr$TA.y - CRMpererr$TA.x)/CRMpererr$TA.y * 100

#plot
ggplot(CRMpererr, aes(Date, percerr, color = substr(CRMpererr$Sample.ID,10,13))) + geom_point() + theme_bw() + ylab("percent error") + scale_x_datetime(breaks = CRMpererr$Date) + theme(axis.text.x=element_text(angle= 90, hjust = 0))

ggplot(CRMpererr[which(CRMpererr$percerr < 1),], aes("CRM",percerr)) +geom_boxplot() + ylab("percent error")
```

TA over time for ambient and low treatments
```{r, echo=FALSE}
###AMB VS. LOW
library(ggplot2)
#line plot TA over time for amb and low on the same plot

ggplot(fall.data[which(fall.data$Mass > 59 & fall.data$treatment == "ambient"| fall.data$treatment == "low" | fall.data$treatment =="varlow"),], aes(Date, TA)) + geom_line(aes(color = tank)) + scale_x_datetime(breaks = fall.data$Date) + theme(axis.text.x=element_text(angle = 90, hjust = 0)) + geom_point(aes(color = tank)) + ggtitle("TA over time colored by tank")

ggplot(fall.data[which(fall.data$Mass > 59 & fall.data$treatment == "ambient"| fall.data$treatment == "low" | fall.data$treatment =="varlow"),], aes(Date, TA)) + geom_line(aes(color = treatment)) + scale_x_datetime(breaks = fall.data$Date) + theme(axis.text.x=element_text(angle = 90, hjust = 0)) + geom_point(aes(color = treatment)) + ggtitle("TA over time colored by treatment")

ggplot(cumu.data[which(cumu.data$Date< as.POSIXct("2018-10-06", format = "%Y-%m-%d" ) & substr(cumu.data$sample.name,0,1) != "J" & substr(cumu.data$sample.name,0,3) != "CRM"),], aes(Date, TA)) + geom_line(aes(color = sample.name)) + scale_x_datetime(breaks = cumu.data$Date) + theme(axis.text.x=element_text(angle = 90, hjust = 0)) + geom_point(aes(color = sample.name)) + ggtitle("Sam's data from summer 2018")
```

Boxplots of all TA measurements (Nov 7-Dec 12) for ambient and low **WATER SAMPLES**
```{r, echo=FALSE}
#boxplot TA x sample name
ggplot(fall.data[which(fall.data$Mass > 59 & fall.data$treatment == "ambient"| fall.data$treatment == "low" | fall.data$treatment == "varlow"),], aes(sample.name, TA)) + geom_boxplot(aes(fill =sample.name))
```

Boxplots of all TA measurements (Nov 7-Dec 12) for ambient and low **TANKS**
```{r, echo=FALSE}
#boxplot TA x tank
ggplot(fall.data[which(fall.data$Mass > 59 & fall.data$treatment == "ambient"| fall.data$treatment == "low" | fall.data$treatment == "varlow"),], aes(tank, TA)) + geom_boxplot(aes(fill =tank))
```

Boxplots of all TA measurements (Nov 7-Dec 12) for ambient and low **TREATMENTS**
```{r, echo=FALSE}
#boxplot TA x tank
ggplot(fall.data[which(fall.data$tank == "1" | fall.data$tank == "2" | fall.data$tank == "3"| fall.data$tank == "4"),], aes(treatment, TA)) + geom_boxplot(aes(fill = treatment))
```

Boxplots of all TA measurements for **Summer 2018**
```{r, echo=FALSE}
#boxplot TA x tank
ggplot(cumu.data[which(cumu.data$Date< as.POSIXct("2018-10-06", format = "%Y-%m-%d" ) & substr(cumu.data$sample.name,0,1) != "J" & substr(cumu.data$sample.name,0,3) != "CRM"),], aes(sample.name, TA)) + geom_boxplot(aes(fill =sample.name)) + theme(axis.text.x=element_text(angle = 90, hjust = 0))
```

```{r, echo = FALSE}
#Is there a significant different between **TANKS** based on TA?
#test to see if treatments are sig. diff
summary(aov(TA ~ tank, data = fall.data[which(fall.data$tank == "1" | fall.data$tank == "2" | fall.data$tank == "3"| fall.data$tank == "4"),]))

TukeyHSD(aov(TA ~ tank, data = fall.data[which(fall.data$tank == "1" | fall.data$tank == "2" | fall.data$tank == "3"| fall.data$tank == "4"),]))
```

```{r, echo = FALSE}
#Is there a significant different between TREATMENTS based on TA?

#test to see if treatments are sig. diff
t.test(x= fall.data[which(fall.data$tank == "3"| fall.data$tank == "4"),"TA"], y =  fall.data[which(fall.data$tank == "1" | fall.data$tank == "2"),"TA"])
```



