---
title: "Untitled"
author: "Shelly Trigg"
date: "12/3/2020"
output: html_document
---

load libraries
```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
```

load data
```{r}
ca_data <- read_xlsx("../data/20201125/CompiledData.xlsx")

sample_info <- read_xlsx("../data/20201125/CompiledData.xlsx", sheet = 'SampleInfo' )
```


calculate the avg abs for each standard
```{r}
ca_data_sum <- ca_data %>% group_by(Plate, ID) %>% summarise(mean_abs = mean(`Absorbance @ 570 (1.0s) (A)`))

```

calculate the corrected absorbance by subtracting STD_A from all measurements
```{r}
ca_data_sum_corrected <- ca_data_sum %>% group_by(Plate) %>% mutate(correct_abs = mean_abs - mean_abs[which(ID == "STD_A")])

```

add column with std concentrations
```{r}
ca_data_sum_corrected$conc <- NA

for (i in 1:nrow(ca_data_sum_corrected)){
  if(ca_data_sum_corrected$ID[i]=="STD_A"){
    ca_data_sum_corrected$conc[i] <- 0
  }
  if(ca_data_sum_corrected$ID[i]=="STD_B"){
    ca_data_sum_corrected$conc[i] <- 0.5
  }
  if(ca_data_sum_corrected$ID[i]=="STD_C"){
    ca_data_sum_corrected$conc[i] <- 1
  }
  if(ca_data_sum_corrected$ID[i]=="STD_D"){
    ca_data_sum_corrected$conc[i] <- 2
  }
  if(ca_data_sum_corrected$ID[i]=="STD_E"){
    ca_data_sum_corrected$conc[i] <- 4
  }
  if(ca_data_sum_corrected$ID[i]=="STD_F"){
    ca_data_sum_corrected$conc[i] <- 6
  }
  if(ca_data_sum_corrected$ID[i]=="STD_G"){
    ca_data_sum_corrected$conc[i] <- 8
  }
  if(ca_data_sum_corrected$ID[i]=="STD_H"){
    ca_data_sum_corrected$conc[i] <- 10
  }
}

```

plot corrected STD abs
```{r}

ggplot(ca_data_sum_corrected[grep("STD",ca_data_sum_corrected$ID),], aes(conc,correct_abs)) + geom_point() + facet_wrap(~Plate)
```

calculate calcium concentration from slope
```{r}

# conc. = (corrected sample abs - y intercept / slope) * sample dilution
for (i in 1:nrow(ca_data_sum_corrected)){
  if(substr(ca_data_sum_corrected$ID[i],1,3)!="STD" & ca_data_sum_corrected$Plate[i] == 1){
    ca_data_sum_corrected$conc[i] <- (ca_data_sum_corrected$correct_abs[i] + 0.0064 / 0.0999) * 4
  }
  if(substr(ca_data_sum_corrected$ID[i],1,3)!="STD" & ca_data_sum_corrected$Plate[i] == 2){
    ca_data_sum_corrected$conc[i] <- (ca_data_sum_corrected$correct_abs[i] + 0.0057 / 0.1067) * 4
  }
  if(substr(ca_data_sum_corrected$ID[i],1,3)!="STD" & ca_data_sum_corrected$Plate[i] == 3){
    ca_data_sum_corrected$conc[i] <- (ca_data_sum_corrected$correct_abs[i] + 0.0038 / 0.1057) * 4
  }
  if(substr(ca_data_sum_corrected$ID[i],1,3)!="STD" & ca_data_sum_corrected$Plate[i] == 4){
    ca_data_sum_corrected$conc[i] <- (ca_data_sum_corrected$correct_abs[i] + 0.0002 / 0.1051) * 4
  }
}

#slope and intercepts
# plate 1:
  # slope: 0.0999
  # intercept: -0.0064

#plate 2: 
  # slope: 0.1067
  # intercept: -0.0057

#plate 3: 
  # slope: 0.1057
  # intercept: -0.0038

#plate 4:
  # slope: 0.1051
  # intercept: -0.0002
```

match up with treatment and time info
```{r}
#first check ID is the exact same as the label
View(sample_info[which(sample_info$ID!= sample_info$Label),])

#now create ID column to match with plate reader data
sample_info$ID <- paste0(substr(sample_info$Date,5,6),"/",substr(sample_info$Date,7,8),"-",sample_info$Label)



#merge sample info with plate reader data
ca_data_sum_corrected_info <- merge(ca_data_sum_corrected, sample_info, by = "ID")


#create a column with the number of sampling points called "freq"
ca_data_sum_corrected_info <- merge(ca_data_sum_corrected_info,table(Label = ca_data_sum_corrected_info$Label), by =  "Label")

#create a column with factors to use for labeling individuals with multiple sampling points

ca_data_sum_corrected_info$name <- factor(ifelse(ca_data_sum_corrected_info$Freq !=1,paste0(ca_data_sum_corrected_info$Label,"_",ca_data_sum_corrected_info$Freq),1))

```

plot

```{r}
ggplot(ca_data_sum_corrected_info, aes(x = factor(Date), y = conc, group = interaction(Treatment,factor(Date)),color = Treatment)) + geom_boxplot(outlier.shape = NA) + geom_point(shape = ca_data_sum_corrected_info$name,size=1,position = position_jitterdodge(jitter.width = 0.2)) + theme_bw() + labs(x = "Date", y = "Calcium conc. (mg/dL)") + scale_shape_manual(values=1:nlevels(ca_data_sum_corrected_info$name))

```
run aov


```{r}
aov_data <- aov(conc ~ Treatment * Date, data = ca_data_sum_corrected_info)
summary(aov_data)

#               Df Sum Sq Mean Sq F value Pr(>F)  
#Treatment       1   2.47  2.4712   3.717 0.0574 .
#Date            1   0.10  0.1040   0.156 0.6935  
#Treatment:Date  1   0.49  0.4912   0.739 0.3926  
#Residuals      81  53.86  0.6649                 
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

```